models/BotScenarios.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "bot_scenarios".
 *
 * @property int $bot_scenario_from_id
 * @property int $bot_scenario_to_id
 *
 * @property BotScenario $botScenarioFrom
 * @property BotScenario $botScenarioTo
 */
class BotScenarios extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bot_scenarios';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['bot_scenario_from_id', 'bot_scenario_to_id'], 'integer'],
            [['bot_scenario_from_id'], 'exist', 'skipOnError' => true, 'targetClass' => BotScenario::className(), 'targetAttribute' => ['bot_scenario_from_id' => 'id']],
            [['bot_scenario_to_id'], 'exist', 'skipOnError' => true, 'targetClass' => BotScenario::className(), 'targetAttribute' => ['bot_scenario_to_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'bot_scenario_from_id' => 'Bot Scenario From ID',
            'bot_scenario_to_id' => 'Bot Scenario To ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBotScenarioFrom()
    {
        return $this->hasOne(BotScenario::className(), ['id' => 'bot_scenario_from_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBotScenarioTo()
    {
        return $this->hasOne(BotScenario::className(), ['id' => 'bot_scenario_to_id']);
    }
}

controllers/BotScenarioController.php
<?php

namespace app\controllers;

use Yii;
use app\models\BotScenario;
use app\models\BotScenarioSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yii\web\UploadedFile;

/**
 * BotScenarioController implements the CRUD actions for BotScenario model.
 */
class BotScenarioController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all BotScenario models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BotScenarioSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single BotScenario model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title'=> "сценарий #".$id,
                'content'=>$this->renderAjax('view', [
                    'model' => $this->findModel($id),
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                    Html::a('Изменить',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
            ];
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new BotScenario model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new BotScenario();
        $model->bot_id = isset($_GET['botId']) ? $_GET['botId'] : null;
        $model->lastScenarioIds = isset($_GET['id']) ? [$_GET['id']] : null;

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Добавить сценарий",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])

                ];
            }else if($model->load($request->post()) && $model->validate()){

                $model->file = UploadedFile::getInstance($model, 'file');

                $model->save(false);

                return [
                    'forceReload'=>'#scenarios-pjax-container',
                    'forceClose' => true
                ];
            }else{
                return [
                    'title'=> "Добавить сценарий",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])

                ];
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }

    }

    /**
     * Updates an existing BotScenario model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Изменить сценарий #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];
            }else if($model->load($request->post())){

                $model->file = UploadedFile::getInstance($model, 'file');

                if($model->save()){
                    return [
                        'forceReload'=>'#scenarios-pjax-container',
                        'forceClose' => true,
                    ];
                } else {
                    var_dump($model->errors);
                    return [
                        'title'=> "Изменить сценарий #".$id,
                        'content'=>$this->renderAjax('update', [
                            'model' => $model,
                        ]),
                        'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                    ];
                }
            }else{
                return [
                    'title'=> "Изменить сценарий #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    public function actionDeleteAttachment($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $result = false;

        if($model->attachment_link != null){
            if(file_exists($model->attachment_link)){
                unlink($model->attachment_link);
                $result = true;
                $model->attachment_link = '';
                $model->save(false);
            } else {
                throw new NotFoundHttpException('Файл не найден');
            }
        }


        return ['result' => $result];
    }

    public function actionCopy($id)
    {
        $request = Yii::$app->request;
        $this->findModel($id)->copy();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#scenarios-pjax-container'];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }
    }

    /**
     * Delete an existing BotScenario model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#scenarios-pjax-container'];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }

    /**
     * Delete multiple existing BotScenario model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionBulkDelete()
    {
        $request = Yii::$app->request;
        $pks = explode(',', $request->post( 'pks' )); // Array or selected records primary keys
        foreach ( $pks as $pk ) {
            $model = $this->findModel($pk);
            $model->delete();
        }

        if($request->isAjax){
            /*

views/bot-scenario/_columns.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'bot_id',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'description',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'external_message_id',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'strict_search_mode',
    ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'customer_status_id',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'repeat',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'any_user_answer',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'no_user_answer',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'no_answer_time',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'bot_answer',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'attachment_link',
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'template' => '{update}{delete}',
        'buttons' => [
            'delete' => function ($url, $model) {
                return Html::a('<i class="fa fa-trash text-danger" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Удалить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                    'data-confirm-title'=>'Вы уверены?',
                    'data-confirm-message'=>'Вы действительно хотите удалить данную запись?'
                ]);
            },
            'update' => function ($url, $model) {
                return Html::a('<i class="fa fa-pencil text-primary" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Изменить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                ])."&nbsp;";
            }
        ],
    ],

];   

views/bot-scenario/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BotScenario */
/* @var $form yii\widgets\ActiveForm */

if($model->isNewRecord == false){
    $model->variants = \yii\helpers\ArrayHelper::getColumn(\app\models\BotScenarioVariant::find()->where(['bot_scenario_id' => $model->id])->all(), 'content');
//    $model->lastScenarioIds = \yii\helpers\ArrayHelper::getColumn(\app\models\BotScenarios::find()->where(['bot_scenario_to_id' => $model->id])->all(), 'bot_scenario_from_id');
    $model->nextScenarioIds = \yii\helpers\ArrayHelper::getColumn(\app\models\BotScenarios::find()->where(['bot_scenario_from_id' => $model->id])->all(), 'bot_scenario_to_id');
}

?>

    <div class="bot-scenario-form">

        <?php $form = ActiveForm::begin(['id' => 'bot-scenario-form', 'options' => ['enctype' => 'multipart/form-data']]); ?>

        <div class="row">
            <div class="col-md-12">
                <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
            </div>
            <!--        <div class="col-md-3">-->
            <?php
            //            /echo $form->field($model, 'lastScenarioIds')->widget(\kartik\select2\Select2::className(), [
            //                'data' => \yii\helpers\ArrayHelper::map($model->getLinkableScenarios(), 'id', 'name'),
            //                'options' => [
            //                    'placeholder' => 'Введите предыдущие сценарии...',
            //                ],
            //                'pluginOptions' => [
            //                    'allowClear' => true,
            //                    'tags' => true,
            //                    'multiple' => true,
            //                ],
            //            ])
            ?>
            <!--        </div>-->
        </div>

        <div class="row">
            <div class="col-md-12">
                <?php echo $form->field($model, 'nextScenarioIds')->widget(\kartik\select2\Select2::className(), [
                    'data' => \yii\helpers\ArrayHelper::map($model->getLinkableScenarios(), 'id', 'name'),
                    'options' => [
                        'placeholder' => 'Введите следующие сценарии...',
                    ],
                    'pluginOptions' => [
                        'allowClear' => true,
                        'tags' => true,
                        'multiple' => true,
                    ],
                ])
                ?>
            </div>
        </div>

        <div class="variants-wrapper" <?=$model->isNewRecord == false && $model->any_user_answer == 1 ? 'style="display: none;"' : ''?>>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'variants')->widget(\kartik\select2\Select2::className(), [
                        'options' => [
                            'placeholder' => 'Введите варианты ответа...',
                        ],
                        'pluginOptions' => [
                            'allowClear' => true,
                            'tags' => true,
                            'multiple' => true,
                        ],
                    ]) ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <?= $form->field($model, 'customer_status_id')->dropDownList(\yii\helpers\ArrayHelper::map(\app\models\CustomerStatus::find()->all(), 'id', 'name'), ['prompt' => 'Выберите статус']) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'file')->fileInput() ?>
            </div>
            <div class="col-md-6">
                <?php if($model->hasFile()): ?>
                    <?php
                    $fileName = explode('/', $model->attachment_link);
                    if(count($fileName) == 2){
                        $fileName = $fileName[1];
                    } else {
                        $fileName = 'error';
                    }
                    ?>
                    <?php if($fileName != 'error'): ?>
                        <p id="file-wrapper">
                            <?php
                            $fileName = explode('.', $fileName);
                            if(count($fileName) == 2){
                                $extension = $fileName[1];
                                echo Html::a("Текущий файл ({$extension})", '/'.$model->attachment_link, ['target' => '_blank', 'style' => 'display: inline-block; margin-top: 35px;']) .
                                    ' ' . Html::a('<i class="fa fa-trash"></i>', ['bot-scenario/delete-attachment', 'id' => $model->id], ['class' => 'text-danger', 'title' => 'Удалить файл', 'style' => 'font-size: 18px;', 'data-role' => 'delete-attachment']);
                            } else {
                                echo '<p class="text-danger">Ошибка</p>';
                            }
                            ?>
                        </p>
                    <?php else: ?>
                        <p class="text-danger">Ошибка</p>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'send_in_crm')->checkbox() ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'strict_search_mode')->checkbox() ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'any_user_answer')->checkbox(['onchange' => 'if($(this).is(":checked")){ $(".variants-wrapper").slideUp(); } else { $(".variants-wrapper").slideDown(); };']) ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'no_user_answer')->checkbox(['onchange' => 'if($(this).is(":checked")){ $(".no-answer-time-wrapper").slideDown(); } else { $(".no-answer-time-wrapper").slideUp(); };']) ?>
            </div>
        </div>

        <div class="no-answer-time-wrapper" <?=$model->isNewRecord || $model->no_user_answer == 0 ? 'style="display: none;"' : ''?>>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'no_answer_time')->input('number') ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'timing_message')->textarea() ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <?= $form->field($model, 'bot_answer')->textarea(['rows' => 6]) ?>
            </div>
        </div>

        <div class="form-group">
            <?= Html::submitButton('Сохранить', ['class' => $model->isNewRecord ? 'btn btn-inverse btn-sm btn-block' : 'btn btn-primary btn-sm btn-block']) ?>
        </div>

        <?php if($model->isNewRecord == false && $model->is_start == false): ?>
            <div class="form-group">
                <?= Html::a('<i class="fa fa-trash"></i> Удалить','#', ['class' => 'btn btn-danger btn-sm btn-block', 'data-delete' => $model->id]) ?>
            </div>
        <?php endif; ?>

        <?php ActiveForm::end(); ?>

    </div>


<?php

$script = <<< JS

$('#bot-scenario-form').unbind('submit');

$('#bot-scenario-form').submit(function(e){
    e.preventDefault();
    
    var form = $(this);
    var url = form.attr('action');
    var formData = new FormData(this);

    $.ajax({
           type: "POST",
           url: url,
           data: formData, // serializes the form's elements.
           processData: false,
            contentType: false,
           success: function(data)
           {
               $.pjax.reload(data.forceReload);
               $('.theme-panel').removeClass('active');
           }
         });
});

$('[data-delete]').click(function(e){
    e.preventDefault();
    
    var id = $(this).data('delete');
    
    $.post('/bot-scenario/delete?id='+id, {'id': id}, function(response){
        $.pjax.reload(response.forceReload);
        $('.theme-panel').removeClass('active');
    });
});

$('[data-role="delete-attachment"]').click(function(e){
    e.preventDefault();

    var url = $(this).attr('href');
    var csrfParam = yii.getCsrfParam;
    var csrfToken = yii.getCsrfToken;

    $.ajax({
        'url': url,
        method: 'POST',
        data: {
            csrfParam: csrfToken,
        },
        success: function(response){
            $('#file-wrapper').text('Файл удален');
        },
        fail: function(response){
            $('#file-wrapper').text(response.message);
        },
    });
});

JS;
$this->registerJs($script, \yii\web\View::POS_READY);

?>

views/bot-scenario/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\BotScenario */

?>
<div class="bot-scenario-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/bot-scenario/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\BotScenarioSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = "Сценарий бота";
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<div class="panel panel-inverse bot-scenario-index">
    <div class="panel-heading">
<!--        <div class="panel-heading-btn">-->
<!--        </div>-->
        <h4 class="panel-title">Сценарий бота</h4>
    </div>
    <div class="panel-body">
        <div id="ajaxCrudDatatable">
            <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'panelBeforeTemplate' =>    Html::a('Добавить <i class="fa fa-plus"></i>', ['create'],
                    ['role'=>'modal-remote','title'=> 'Добавить сценарий','class'=>'btn btn-success']).'&nbsp;'.
                Html::a('<i class="fa fa-repeat"></i>', [''],
                    ['data-pjax'=>1, 'class'=>'btn btn-white', 'title'=>'Обновить']),
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'panel' => [
            'headingOptions' => ['style' => 'display: none;'],
            'after'=>BulkButtonWidget::widget([
            'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Удалить',
            ["bulk-delete"] ,
            [
            "class"=>"btn btn-danger btn-xs",
            'role'=>'modal-remote-bulk',
            'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
            'data-request-method'=>'post',
            'data-confirm-title'=>'Вы уверены?',
            'data-confirm-message'=>'Вы действительно хотите удалить данный элемент?'
            ]),
            ]).
            '<div class="clearfix"></div>',
            ]
            ])?>
        </div>
    </div>
</div>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/bot-scenario/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\BotScenario */
?>
<div class="bot-scenario-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/bot-scenario/view.php
<?php

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\BotScenario */
?>
<div class="bot-scenario-view">
 
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'bot_id',
            'name',
            'description:ntext',
            'strict_search_mode',
            'customer_status_id',
            'repeat',
            'any_user_answer',
            'no_user_answer',
            'no_answer_time:datetime',
            'bot_answer:ntext',
            'attachment_link',
        ],
    ]) ?>

</div>